#! /usr/bin/env ruby

require 'erb'
require 'fileutils'

include FileUtils

name = ARGV[0]
has_css = true
has_js = true
mkdir("#{name}")
touch("#{name}/#{name}.html")


File.open( "templates/template.html.rhtml" ) do |f|
           erb = ERB.new( f.read )
           x = erb.result(binding)
           File.open( "#{name}/#{name}.html", 'w' ) do |hfile|
                      hfile.write x
           end
end

cp("templates/program.js.rhtml", "#{name}/#{name}.js") if has_js
cp("templates/style.css.rhtml", "#{name}/#{name}.css") if has_css
